#!/bin/bash

for dotfile in $(find . -maxdepth 1 -mindepth 1 | cut -b3-)
do
    if [[ "$dotfile" != $(basename "$0") ]] \
        && [[ "$dotfile" != ".git" ]] \
        && [[ "$dotfile" != ".gitmodules" ]] \
        && [[ "$dotfile" != ".svn" ]]
    then
        fulldotfile=$(readlink -f "$dotfile")
        homedotfile="$HOME/$dotfile"
        if [[ -e "$homedotfile" ]]; then
            if [[ "$fulldotfile" != $(readlink -f "$homedotfile") ]]; then
                echo "Not overriding existing file '$homedotfile'"
            fi
        else
            echo "Creating symlink '$homedotfile'"
            ln -s "$fulldotfile" "$homedotfile"
        fi
    fi
done
